import '../global.css';
import '@fmicodes/fmicodes-ui/global.css';

import React from 'react';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { ThemeProvider } from '@fmicodes/fmicodes-ui/lib/providers/theme-provider';
import { routing } from 'apps/fmicodes-admin/i18n/routing';

export const metadata = {
  title: 'Welcome to fmicodes-admin',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!(routing.locales as readonly string[]).includes(locale)) {
    notFound();
  }

  const messages = useMessages();
  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <html lang={locale}>
        <body>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
