version: '3'

services:
  database:
    image: postgres
    restart: 'no'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fmicodes

  redis:
    image: redis
    restart: 'no'
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: redis
