name: 'Documentation Sync'

on:
  push:
    branches:
      - main
    paths:
      - 'docs/wiki/**'
  repository_dispatch:
    types: [docs]
  gollum:

env:
  GIT_AUTHOR_NAME: Faculty Student Council at FMI
  GIT_AUTHOR_EMAIL: fss.fmi.uni.sofia@gmail.com

jobs:
  sync-repository-to-wiki:
    name: 'Sync repository to wiki'
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Commit Message
        run: |
          # Only use the heading of the commit
          echo COMMIT_MESSAGE="${{ github.event.head_commit.message }}" | cut -d$'\n' -f1 >> $GITHUB_ENV

      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: docs/wiki
          destination: wiki
          token: ${{ secrets.FSS_FMI_GITHUB_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          commitMessage: |-
            ${{ env.COMMIT_MESSAGE }}

  sync-wiki-to-repository:
    name: 'Sync wiki to repository'
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DOCUMENTATION_SYNC_GITHUB_TOKEN }}
          ref: main

      - name: Set Commit Message
        run: |
          if [ ${{ github.event.pages[0].summary }} ];
          then echo COMMIT_MESSAGE="${{ github.event.pages[0].summary }}" >> $GITHUB_ENV;
          else echo COMMIT_MESSAGE="docs: sync wiki pages to the repository" >> $GITHUB_ENV;
          fi

      - name: Sync wiki to docs
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki
          destination: docs/wiki
          token: ${{ secrets.DOCUMENTATION_SYNC_GITHUB_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: main
          commitMessage: |-
            ${{ env.COMMIT_MESSAGE }}

            This commit was automatically generated to sync wiki pages to the repository.
